apiVersion: v1
items:
- apiVersion: http.keda.sh/v1alpha1
  kind: HTTPScaledObject
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"http.keda.sh/v1alpha1","kind":"HTTPScaledObject","metadata":{"annotations":{},"name":"frontend-httpscaledobject","namespace":"default"},"spec":{"hosts":["34.59.95.223"],"replicas":{"max":10,"min":0},"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"frontend","port":80,"service":"frontend"},"targetPendingRequests":10}}
    creationTimestamp: "2025-11-05T18:15:15Z"
    finalizers:
    - httpscaledobject.http.keda.sh
    generation: 3
    name: frontend-httpscaledobject
    namespace: default
    resourceVersion: "2214821"
    uid: f0023d60-5504-4968-bc8b-0c6dbd785c17
  spec:
    hosts:
    - 35.202.208.160
    replicas:
      max: 10
      min: 0
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: frontend
      port: 80
      service: frontend
    targetPendingRequests: 10
  status:
    conditions:
    - message: Identified HTTPScaledObject creation signal
      reason: PendingCreation
      status: Unknown
      timestamp: "2025-11-06T16:28:07Z"
      type: Ready
    - message: App ScaledObject created
      reason: AppScaledObjectCreated
      status: "True"
      timestamp: "2025-11-06T16:28:07Z"
      type: Ready
    - message: Finished object creation
      reason: HTTPScaledObjectIsReady
      status: "True"
      timestamp: "2025-11-06T16:28:07Z"
      type: Ready
    targetService: frontend:80
    targetWorkload: apps/v1/Deployment/frontend
kind: List
metadata:
  resourceVersion: ""
