apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: keda-http-add-on
    meta.helm.sh/release-namespace: keda
  creationTimestamp: "2025-11-03T05:52:29Z"
  generation: 5
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/instance: keda-http-add-on
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-add-ons-http
    app.kubernetes.io/version: 0.10.0
    helm.sh/chart: keda-add-ons-http-0.10.0
  name: keda-add-ons-http-interceptor
  namespace: keda
  resourceVersion: "1784207"
  uid: 3fd37cf5-894a-419d-9df2-d2dbb498c5b8
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: interceptor
      app.kubernetes.io/instance: keda-http-add-on
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: keda-add-ons-http
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-05T17:27:54Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: interceptor
        app.kubernetes.io/instance: keda-http-add-on
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: keda-add-ons-http
        app.kubernetes.io/version: 0.10.0
        helm.sh/chart: keda-add-ons-http-0.10.0
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=rfc3339
        env:
        - name: KEDA_HTTP_CURRENT_NAMESPACE
          value: keda
        - name: KEDA_HTTP_PROXY_PORT
          value: "8080"
        - name: KEDA_HTTP_ADMIN_PORT
          value: "9090"
        - name: KEDA_HTTP_CONNECT_TIMEOUT
          value: 500ms
        - name: KEDA_HTTP_KEEP_ALIVE
          value: 1s
        - name: KEDA_RESPONSE_HEADER_TIMEOUT
          value: 500ms
        - name: KEDA_CONDITION_WAIT_TIMEOUT
          value: 20s
        - name: KEDA_HTTP_ENDPOINTS_CACHE_POLLING_INTERVAL_MS
          value: "250"
        - name: KEDA_HTTP_FORCE_HTTP2
          value: "false"
        - name: KEDA_HTTP_MAX_IDLE_CONNS
          value: "100"
        - name: KEDA_HTTP_IDLE_CONN_TIMEOUT
          value: 90s
        - name: KEDA_HTTP_TLS_HANDSHAKE_TIMEOUT
          value: 10s
        - name: KEDA_HTTP_EXPECT_CONTINUE_TIMEOUT
          value: 1s
        image: ghcr.io/kedacore/http-add-on-interceptor:0.10.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: proxy
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: keda-add-ons-http-interceptor
        ports:
        - containerPort: 9090
          name: admin
          protocol: TCP
        - containerPort: 8080
          name: proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: proxy
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 64Mi
          requests:
            cpu: 250m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        supplementalGroups:
        - 1000
      serviceAccount: keda-add-ons-http-interceptor
      serviceAccountName: keda-add-ons-http-interceptor
      terminationGracePeriodSeconds: 10
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-11-03T05:52:51Z"
    lastUpdateTime: "2025-11-03T05:52:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-03T05:52:29Z"
    lastUpdateTime: "2025-11-05T18:15:08Z"
    message: ReplicaSet "keda-add-ons-http-interceptor-9bf9b5b68" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
