apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: weekday-short-sleep
  namespace: default
spec:
  weekdays: "1-5"          # Monday to Friday
  sleepAt: "00:02"
  wakeUpAt: "00:10"
  timeZone: "Asia/Kolkata"
  suspendCronJobs: true    # if you also want CronJobs stopped
  # suspendDeployments: true   # default: true
  # suspendStatefulSets: true  # default: true
