apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: adservice-scaledobject
  namespace: default
spec:
  hosts:
    - "34.59.95.223"
  scaleTargetRef:
    name: adservice
    kind: Deployment
    apiVersion: apps/v1
    service: adservice
    port: 9555
  replicas:
    min: 0
    max: 10
  targetPendingRequests: 10
