apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: checkoutservice-scaledobject
  namespace: default
spec:
  hosts:
    - "34.59.95.223"
  scaleTargetRef:
    name: checkoutservice
    kind: Deployment
    apiVersion: apps/v1
    service: checkoutservice
    port: 5050
  replicas:
    min: 0
    max: 10
  targetPendingRequests: 10
