apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: recommendationservice-scaledobject
spec:
  scaleTargetRef:
    name: recommendationservice
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: frontend_up
      query: kube_deployment_status_replicas{deployment="frontend",namespace="default"} > 0
      threshold: '1'
