apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frontend-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: frontend
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 120  # wait 2 minutes before scaling down
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local:80
      metricName: nginx_ingress_controller_nginx_process_requests_total
      threshold: "26"  # scale up if requests > 5 per scrape interval
      query: |
        increase(nginx_ingress_controller_nginx_process_requests_total[2m])
  - type: cpu
    metadata:
      type: Utilization
      value: "30"   # scale up if CPU > 60%
